version: '3'

services:
  blockscout:
    image: blockscout:${BLOCKSCOUT_VERSION:-latest}
    build:
      context: .
      args:
        - COIN=ETH
        - BLOCKSCOUT_VERSION=${BLOCKSCOUT_VERSION}
        - SOLJSON_VERSION=${SOLJSON_VERSION}
    ports:
     - 4000:4000
    env_file:
      - .env-explorer
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?ssl=false
      - ECTO_USE_SSL=false
      - ETHEREUM_JSONRPC_VARIANT=ganache
      # default port, if not passed, 8545
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:${GPORT:-8545}
      - ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:${GPORT:-8545}
      - INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER=true
    extra_hosts: 
      - host.docker.internal:host-gateway
    entrypoint: '/bin/sh -c "mix do ecto.create, ecto.migrate; mix phx.server"'
    depends_on:
      - postgres
    volumes:
      - "solcvolume:/opt/app/_build/prod/lib/explorer/priv/solc_compilers"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - "dbvolume:/var/lib/postgresql/data"

volumes:
  dbvolume:
  solcvolume:
